// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtduodrzsawcxtfvajec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0ZHVvZHJ6c2F3Y3h0ZnZhamVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDY5NTUsImV4cCI6MjA3MDU4Mjk1NX0.cbrcwhqTl-QpuM9p2YbojEWxzQwVBJR0rDE3HwRK_pY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});